### ISSUE TITLE
"You are running winetricks-20230212-next, latest upstream is winetricks-20240105!" message when selecting game

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [flathub/com.github.Matoking.protontricks#105]
When I launch protontricks and select a game, first I get the message "You are running winetricks-20230212-next, latest upstream is winetricks-20240105!":
![изображение](https://github.com/flathub/com.github.Matoking.protontricks/assets/43478602/cece603d-00f2-47eb-a162-f37020cad185)
And the next message says something about self-update:
![изображение](https://github.com/flathub/com.github.Matoking.protontricks/assets/43478602/1f907dba-b936-4202-944f-5f059c7c3647)

I am using gnome-software for managing flatpak apps and I don't have an update for protontricks available.

**Comment by Matoking** [comment]
The Flatpak version of Protontricks ships its own copy of Winetricks that cannot be updated, so this update checker should probably be disabled. I'll look into it.

There's a "Unknown file arch: 65" issue in the newer Winetricks version that will have to be resolved in some way before the bundled Winetricks can be updated, though. There's more information about it in Matoking/protontricks#274.

**Comment by Matoking** [comment]
I've updated the bundled Winetricks to disable the version check. The update should go live in a few hours.
