### ISSUE TITLE
Wont start at all - bug

### ISSUE THREAD

**Issue by Ud4ba** [flathub/com.github.Matoking.protontricks#18]
Protontricks was closed due to the following error:

Found no games. You need to launch a game at least once before Protontricks can find it.

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.5.
Found Steam directory at /home/user/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/user/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Steam library folder /media/user/HARDDRIVE/SteamLibrary not found. Protontricks might not have access to the directory.
Currently logged-in Steam user: USER
Couldn't find custom shortcuts. Maybe none have been created yet?

**Comment by Matoking** [comment]
The log states that `/media/user/HARDDRIVE/SteamLibrary` could not be found by Protontricks. Protontricks Flatpak only has access to default Steam installation directories by default.

See [here for instructions](https://github.com/flathub/com.github.Matoking.protontricks/#configuration):

> In order to grant access to other directories, you can use the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) graphical utility or the [flatpak override](https://docs.flatpak.org/en/latest/flatpak-command-reference.html?highlight=override#flatpak-override) command (eg. `flatpak override --user --filesystem=<PATH> com.github.Matoking.protontricks`) to grant access to other directories.
>
> For example, to grant access to `/mnt/MySSD/SteamLibrary`, you can run the following command:
>
> ```
> flatpak override --user --filesystem=/mnt/MySSD/SteamLibrary com.github.Matoking.protontricks
> ```

Ideally, Protontricks would ask for the permissions automatically, but that doesn't appear possible with Flatpak at the moment. Another option is to give Protontricks filesystem access to everything by default, but that would greatly reduce the security offered by the Flatpak sandbox.
