### ISSUE TITLE
GLIBC_2.34 not found

### ISSUE THREAD

**Issue by JoshuaFern** [flathub/com.github.Matoking.protontricks#34]
Hi, trying to use protontricks but running into this error:

warning: /home/jdf/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/proton_ge_flatpak/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "/app/share/steam/compatibilitytools.d/Proton-GE/dist/bin/wine: /app/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/share/steam/compatibilitytools.d/Proton-GE/dist/bin/wine)"

**Comment by Matoking** [comment]
That Proton installation seems to require glibc 2.34, which the Freedesktop 21.08 runtime didn't have. I've updated the app to use 22.08 runtime which comes with glibc 2.34.

The update should go live in a few hours, let me know if it works afterwards.

**Comment by JoshuaFern** [comment]
Thanks, seems to be working now.
