### ISSUE TITLE
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

### ISSUE THREAD

**Issue by malefooo** [flathub/com.github.Matoking.protontricks#37]
![Screenshot_20221109_125415](https://user-images.githubusercontent.com/31642966/200741950-bf4272a6-3219-4f3e-9430-1a8667fd7d7b.png)

i select the game after opening protontricks and click ok, this will appear, how can i deal with it

**Comment by Matoking** [comment]
It's an expected warning caused by Winetricks and it can be ignored. Proton uses 64-bit prefixes for every game, which is why this warning is shown.
